#ifndef AOTNOTE_H
#define AOTNOTE_H

// QT main window parent class
#include <QMainWindow>

// QT-in-namespace macro to handle some QT config edge cases
QT_BEGIN_NAMESPACE
// Default namespace for code generated by .ui files
namespace Ui {
// Pre-declare generated ui class
class AOTNote;
}
QT_END_NAMESPACE

// Inherit from QMainWindow
class AOTNote : public QMainWindow
{
    // Declare class as a QObject, and thus inherit QT functionality
    Q_OBJECT

public:
    // Constructor that takes the class's parent class, default to nullptr because this is the top level
    AOTNote(QWidget *parent = nullptr);
    // Destructor that we must implement ourselves (no defaults provided by QObject)
    ~AOTNote();

private slots:
    void on_actionNew_triggered();

private:
    // Member is a pointer to an instance of the generated ui class (Not itself)
    Ui::AOTNote *ui;
};
#endif // AOTNOTE_H
